# Generated by Django 3.0.8 on 2020-11-20 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.IntegerField()),
                ('nome', models.CharField(max_length=256)),
                ('data_nascimento', models.DateField()),
                ('tel_residencial', models.IntegerField(validators=[django.core.validators.MinValueValidator(999999999, 'Insira um telefone válido, ex: 11987654321'), django.core.validators.MaxValueValidator(100000000000, 'Insira um telefone válido, ex: 11987654321')])),
                ('tel_comercial', models.IntegerField(validators=[django.core.validators.MinValueValidator(999999999, 'Insira um telefone válido, ex: 11987654321'), django.core.validators.MaxValueValidator(100000000000, 'Insira um telefone válido, ex: 11987654321')])),
                ('end_residencial', models.CharField(max_length=256)),
                ('facebook', models.URLField(max_length=256)),
                ('linkedin', models.URLField(max_length=256)),
                ('twitter', models.URLField(max_length=256)),
                ('instagram', models.URLField(max_length=256)),
                ('CPF', models.IntegerField(validators=[django.core.validators.MinValueValidator(999999999999, 'Insira um CPF válido'), django.core.validators.MaxValueValidator(10000000000000, 'Insira um CPF válido')])),
                ('RG', models.IntegerField(validators=[django.core.validators.MinValueValidator(99999999, 'Insira um RG válido'), django.core.validators.MaxValueValidator(1000000000, 'Insira um RG válido')])),
            ],
        ),
    ]
