# Generated by Django 3.0.8 on 2020-11-20 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CPF',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(9999999999, 'Insira um CPF válido, ex: 123.456.789-01'), django.core.validators.MaxValueValidator(100000000000, 'Insira um CPF válido, ex: 123.456.789-01')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='RG',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(99999999, 'Insira um RG válido, ex: 12.345.678-9'), django.core.validators.MaxValueValidator(1000000000, 'Insira um RG válido, ex: 12.345.678-9')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_comercial',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(999999999, 'Insira um telefone válido, ex: 11987654321'), django.core.validators.MaxValueValidator(100000000000, 'Insira um telefone válido, ex: 11987654321')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_residencial',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(999999999, 'Insira um telefone válido, ex: 11987654321'), django.core.validators.MaxValueValidator(100000000000, 'Insira um telefone válido, ex: 11987654321')]),
        ),
    ]
