# Generated by Django 3.0.8 on 2020-11-20 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201120_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='end_comercial',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_comercial',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(999999999, 'Insira um telefone válido, ex: 11987654321'), django.core.validators.MaxValueValidator(100000000000, 'Insira um telefone válido, ex: 11987654321')]),
        ),
    ]
