# Generated by Django 3.1.3 on 2020-11-20 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201120_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='end_residencial',
            new_name='endereco_residencial',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='end_comercial',
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco_comercial',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CPF',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(9999999999, 'Insira um CPF válido, ex: 123.456.789-01'), django.core.validators.MaxValueValidator(100000000000, 'Insira um CPF válido, ex: 123.456.789-01')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='RG',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(99999999, 'Insira um RG válido, ex: 12.345.678-9'), django.core.validators.MaxValueValidator(1000000000, 'Insira um RG válido, ex: 12.345.678-9')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='facebook',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instagram',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='linkedin',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_comercial',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(999999999, 'Insira um telefone válido, ex: 11987654321'), django.core.validators.MaxValueValidator(100000000000, 'Insira um telefone válido, ex: 11987654321')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_residencial',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(999999999, 'Insira um telefone válido, ex: 11987654321'), django.core.validators.MaxValueValidator(100000000000, 'Insira um telefone válido, ex: 11987654321')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='twitter',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
